# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
  vi:
    languageName: Tiếng Việt
    languageDirection: ltr
    languageCode: vi-VN # Mã vùng ngôn ngữ (Giúp SEO tốt hơn trên Google Việt Nam)
    title: Vật lí - toán
    params: 
      description: "Blog cá nhân lưu trữ đề thi, tài liệu học tập và bài viết tham khảo về Vật lí, Vật lí lượng tử, Cơ học giải tích và Toán học dành cho sinh viên."
  #en:
    #languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
#zh:
#  languageCode: zh-Hans
#  contentDir: content/zh
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
